# Generated by Django 2.0.6 on 2018-06-08 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=50)),
                ('num_sensors', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(default='Unknown', max_length=100)),
                ('type_text', models.CharField(max_length=100)),
                ('room_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.Room')),
            ],
        ),
    ]
