# Generated by Django 2.0.6 on 2018-06-10 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_auto_20180609_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=100)),
                ('type_list', models.CharField(choices=[('Controller', 'Controller'), ('Sensor', 'Sensor'), ('Other', 'Other')], max_length=50)),
                ('location_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.Location')),
            ],
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='room_key',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
